/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tictactoe;


import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author whisn
 */
public class TicTacToe extends javax.swing.JFrame {
    Random rand = new Random();
    List<JButton> listBtn = new ArrayList<>();
    List<Integer> humanBlock = new ArrayList<>();
    List<Integer> computerBlock = new ArrayList<>();
    Integer human = -1, computer = -1, emptyBlock = 9, isWin=0;
    
    
    
    ArrayList<ArrayList<Integer> > x = new ArrayList<>();

//     POLA MENANG 0, 1, 2 | 3, 4, 5 | 6, 7, 8 | ||| 0, 3, 6 | 1, 4, 7, 
    /**
     * Creates new form TicTacToeFrame
     */
    
    
    public TicTacToe() {
        initComponents();
                
        listBtn.add(btn1);
        listBtn.add(btn2);
        listBtn.add(btn3);
        listBtn.add(btn4);
        listBtn.add(btn5);
        listBtn.add(btn6);
        listBtn.add(btn7);
        listBtn.add(btn8);
        listBtn.add(btn9);
        
        x.add(new ArrayList<Integer>(Arrays.asList(0, 1, 2)));
        x.add(new ArrayList<Integer>(Arrays.asList(3, 4, 5)));
        x.add(new ArrayList<Integer>(Arrays.asList(6, 7, 8)));
        x.add(new ArrayList<Integer>(Arrays.asList(0, 3, 6)));
        x.add(new ArrayList<Integer>(Arrays.asList(1, 4, 7)));
        x.add(new ArrayList<Integer>(Arrays.asList(2, 5, 8)));
        x.add(new ArrayList<Integer>(Arrays.asList(0, 4, 8)));
        x.add(new ArrayList<Integer>(Arrays.asList(2, 4, 6)));
        
        
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    private void checkWinPattern() {
//        for(int i = 0; i <)
//    }
    private void winCheck() {
//          isWin = 1;
        if(isWin == 0 && !humanBlock.isEmpty()) {
            for(Integer i = 0; i < x.size(); i++) {
                if(humanBlock.containsAll(x.get(i))) {
                    JOptionPane.showMessageDialog(null, "Human Win !! \n Pattern : " + x.get(i));
                    isWin = 1;
                }
            }
        }
        
        if(isWin == 0 && !computerBlock.isEmpty()) {
            for(Integer i = 0; i < x.size(); i++) {
                if(computerBlock.containsAll(x.get(i))) {
                    JOptionPane.showMessageDialog(null, "Computer Win !! \n Pattern : " + x.get(i));
                    isWin = 1;
                }
            }
        }
        
        if(isWin == 0   && emptyBlock == 0) {
            JOptionPane.showMessageDialog(null, "Drawww");
        }
    }
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHuman = new javax.swing.JButton();
        btnComputer = new javax.swing.JButton();
        turnLabel = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn1.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btn1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn1PropertyChange(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn2.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        btn2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn2PropertyChange(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn3.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        btn3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn3PropertyChange(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn4.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        btn4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn4PropertyChange(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn5.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        btn5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn5PropertyChange(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn6.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        btn6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn6PropertyChange(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn7.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        btn7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn7PropertyChange(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn8.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        btn8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn8PropertyChange(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn9.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btn9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        btn9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn9PropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("WHO PLAYED FIRST ?");

        btnHuman.setText("Human");
        btnHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumanActionPerformed(evt);
            }
        });

        btnComputer.setText("Computer");
        btnComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputerActionPerformed(evt);
            }
        });

        turnLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        turnLabel.setText("WHOS TURN");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHuman)
                        .addGap(18, 18, 18)
                        .addComponent(btnComputer)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(turnLabel))
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuman)
                            .addComponent(btnComputer))
                        .addGap(37, 37, 37)
                        .addComponent(turnLabel)
                        .addGap(46, 46, 46)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        winCheck();
//        JOptionPane.showMessageDialog(null, "Computer Win !! \n Pattern : " + isWin);      
        if(human == 1 && isWin == 0 && btn1.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(0);
            btn1.setText("X");
        } 
        winCheck();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn2.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(1);
            btn2.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn3.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(2);
            btn3.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn4.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(3);
            btn4.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn5.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(4);
            btn5.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn6.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(5);
            btn6.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn7.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(6);
            btn7.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn8.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(7);
            btn8.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        winCheck();
        if(human == 1 && isWin == 0 && btn9.getText().length() < 1) {
            human = 0;
            computer = 1;
            emptyBlock -= 1;
            humanBlock.add(8);
            btn9.setText("X");
        }
        winCheck();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumanActionPerformed
        // TODO add your handling code here:
        human = 1;
        computer = 0;
        turnLabel.setText("Your Turn");
        JOptionPane.showMessageDialog(null, "Human First");
//        this.setVisible(false);
    }//GEN-LAST:event_btnHumanActionPerformed

    private void btnComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputerActionPerformed
        // TODO add your handling code here:
        computer = 1;
        human = 0;
        turnLabel.setText("Computer Turn");
        if(computer == 1) {
            computer = 0;
            human = 1;
            Integer i = rand.nextInt(9);
            while(listBtn.get(i).getText().length() > 0) {
                i = rand.nextInt(9);
            }
            computerBlock.add(i);
            listBtn.get(i).setText("O");
            emptyBlock -= 1;
        }
//        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Computer First");
        
    }//GEN-LAST:event_btnComputerActionPerformed

    private void btn1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn1PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
        
    }//GEN-LAST:event_btn1PropertyChange

    private void btn6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn6PropertyChange
        // TODO add your handling code here:        
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn6PropertyChange

    private void btn2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn2PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn2PropertyChange

    private void btn3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn3PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn3PropertyChange

    private void btn4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn4PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn4PropertyChange

    private void btn5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn5PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn5PropertyChange

    private void btn7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn7PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn7PropertyChange

    private void btn8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn8PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn8PropertyChange

    private void btn9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn9PropertyChange
        // TODO add your handling code here:
        winCheck();
        if(emptyBlock > 0 && isWin == 0) {
            if(computer == 1 && evt.getNewValue().equals("X")) {
                    computer = 0;
                    human = 1;
                    Integer i = rand.nextInt(9);
                    while(listBtn.get(i).getText().length() > 0) {
                        i = rand.nextInt(9);
                    }
                    computerBlock.add(i);
                    listBtn.get(i).setText("O");
                    emptyBlock -= 1;
                    winCheck();
            }
        }
    }//GEN-LAST:event_btn9PropertyChange

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < listBtn.size(); i++) {
            listBtn.get(i).setText("");
        }
        
        humanBlock.clear();
        computerBlock.clear();
        human = -1;
        computer = -1; 
        emptyBlock = 9;
        isWin=0;
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnComputer;
    private javax.swing.JButton btnHuman;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
